version: '3.8'

services:
  sentry-mcp:
    build:
      context: .
      dockerfile: custom-sentry-dockerfile
    ports:
      - "9000:8000"  # 別のポートを使用して既存のサービスと競合しないようにします
    volumes:
      - ./sentry/data:/data  # データ保存用のボリューム
    environment:
      - SENTRY_ORG=${SENTRY_ORG}
    command: ["python", "-m", "mcp_server_sentry", "--auth-token", "${SENTRY_API_TOKEN}"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 